### ISSUE TITLE
Allow customization of lineHeight

### ISSUE THREAD

**Issue by canastro** [chargebee/chargebee-js-wrappers#30]
Currently with the customizations I had to do to fit my app's style I need to be able to customize the input's lineHeight, otherwise I get the following  weird scrollbars on firefox:
<img width="383" alt="Screen Shot 2020-11-12 at 15 01 00" src="https://user-images.githubusercontent.com/1267623/98983860-5119fd80-2519-11eb-9582-12cb1bbb70bc.png">

To see this issue in action you can use the following [codesandbox](https://codesandbox.io/s/chargebee-with-mateiral-ui-bi7fx), you'll need to add a test credentials on the [config file](https://codesandbox.io/s/chargebee-with-mateiral-ui-bi7fx?file=/src/config.ts). Make sure to open this in firefox and in the [full window mode](https://bi7fx.csb.app/).

Is it possible to add lineHeight to the whitelisted styles?

**Comment by apennell** [comment]
This is a big issue for us as well--the expiration and CVV fields show a vertical scroll in Safari and Firefox. We even get a horizontal scroll on the card input in Safari in certain conditions, which then makes a vertical scroll appear because the horizontal scroll takes up half of the input field (which is then barely usable). In that case, it looks like there's an issue with the size of the credit card icon being incorrect.

@cb-jose If your team doesn't plan to fix this issues, do you accept pull requests? This is an easy fix and a huge bug for us.

**Comment by RyanWarner** [comment]
For anyone stumbling upon this issue, I contacted support via their in-app chat on Feb 2 2021. Their response was a very vague "this issue was not prioritized."

Why was that not communicated here, whenever that decision was made? Will this issue ever get fixed? I guess time will tell!

**Comment by RyanWarner** [comment]
@canastro did you ever find a workaround?

**Comment by cb-dinesh** [comment]
Hey @canastro / @RyanWarner It is possible to add lineHeight as a customizable style property. We'll roll out an update before the end of next week. This feature has to be added to Chargebee.js first, before it's available in the JS wrappers.

**Comment by cb-abhishek** [comment]
The feature has been implemented.
usage:
```
style: {
     .. base: {
          lineHeight: ‘1.2em’,
     }
 }
...
<CardComponent .. styles={style}../>
```

We will this to the documentation shortly.
