### ISSUE TITLE
Support for Angular 11

### ISSUE THREAD

**Issue by bgpedersen** [chargebee/chargebee-js-wrappers#49]
Installing the package in Angular 11 project, NPM gives dependency error for Angular 10.1.1

![error](https://user-images.githubusercontent.com/3582953/115509164-680a0c00-a27e-11eb-8b90-cfda3b39c3d4.jpg)

If force installing the library, and implemented the Module, an error occurs in the web console

![image](https://user-images.githubusercontent.com/3582953/115508778-ffbb2a80-a27d-11eb-8f58-c778247e9c36.png)

**Comment by cb-dinesh** [comment]
Hi @bgpedersen, This error is due to Chargebee.js trying to initialise before `document.body` is loaded. You can do the following to solve this.

Add Chargebee Angular module in `app.module.ts`:

```
import { ChargebeeJsAngularWrapperModule } from '@chargebee/chargebee-js-angular-wrapper';
...
@NgModule({
  ...
  imports: [
    ...
    ChargebeeJsAngularWrapperModule
  ],
  ...
})
```

**Initialise Chargebee.js on constructor of your component:** `app.component.ts`

```
export class AppComponent {
  cardComponent = null;
  ...
  constructor() {
    window['Chargebee'].init({
      site: 'your-site',
      publishableKey: 'publishable-key'
    })
  }

  onReady = (cardComponent) => {
    this.cardComponent = cardComponent;
  }

  onTokenize = (event) => {
    event.preventDefault();
    
    this.cardComponent.tokenize().then(data => {
      console.log('chargebee token', data.token)
    });
  }
}
```

`app.component.html`
```
  <div cbCardField id='card-field' (ready)="onReady($event)"></div>
  <button (click)="onTokenize($event)">Submit</button>
```

Also, `npm i --save @chargebee/chargebee-js-angular-wrapper` is not throwing any dependency error for Angular 11, can you please confirm if you are still facing this issue?

**Comment by mhombach** [comment]
@bgpedersen is this issue still open? If not, please close.
